### ISSUE TITLE
[Feat]#102 - 배포 전 세부 수정

### ISSUE THREAD

**Issue by SeokJin-0318** [Run-Eat/Run-It#102]
## To-do

- [x] 이메일 회원 탈퇴 시 dismiss 
- [x] 회원가입 애플 로그인 버튼 기능 부여
- [x] 이메일 찾기 버튼 삭제
- [x] UI 수정
