### ISSUE TITLE
[Fix]#127 - Layout, DarkMode

### ISSUE THREAD

**Issue by futuremouse** [Run-Eat/Run-It#127]
## To-do

- [x] 즐겨찾기뷰 상단 수정
- [x] 프로필뷰 상단 수정
- [x] 활동기록 셀 간격 조정
- [x] 로그인 텍스트 하얀색으로 나오는 것 수정, 애플로고 코드로 수정
- [x] 웨더킷 이미지 다크모드일때 하얀색으로 수정, 코드로 수정
