### ISSUE TITLE
[Feat]#135- 편의시설 버튼 쓰로틀과 디바운스 적용

### ISSUE THREAD

**Issue by VesselWheel** [Run-Eat/Run-It#135]
## To-do

- [x] 편의점 버튼은 쓰로틀 3초 적용
- [x] 카페와 건강식 버튼은 디바운스 1초 적용
- [x] 편의시설 query 결과를 캐싱처리하여 반복 호출 시 스택에 저장된 데이터 호출
