### ISSUE TITLE
[Feat]#22 - 회원가입 / 내 정보 Fix

### ISSUE THREAD

**Issue by SeokJin-0318** [Run-Eat/Run-It#22]
## To-do

- [x] 회원가입 시 정규 표현식을 이용한 유효성 검사 -> 미충족 시 회원가입 버튼 비활성화
- [x] 로그인 시 어떤 방식으로 로그인 했는지 표시
- [x] 내 정보 내의 프로필 사진 설정 시 이미지 뷰에 맞게 조정
