### ISSUE TITLE
[Feat]#25 - Connect from RunningMapview to RunningTimerView

### ISSUE THREAD

**Issue by VesselWheel** [Run-Eat/Run-It#25]
## To-do

- [x] RunningMapview와 RunningTimerView연결을 위한 RunningMapview의 버튼 코드 수정 
- [x] 러닝관련 버튼 색 변경 : systemIndio
- [x] 탭 순서 변경 : 러닝(0), 즐겨찾기(1), 내정보(2)
