### ISSUE TITLE
[Feat]#27 - 프로필 / 활동기록, 활동기록상세

### ISSUE THREAD

**Issue by futuremouse** [Run-Eat/Run-It#27]
## To-do

- [x] 활동기록 List를 저장된 리스트로 불러오는 함수 (CoreData) 이용하여 구현
- [x] 활동기록에 날짜 대신 사용자라벨로 라벨이름 변경
- [x] 해당 활동기록셀을 누르면  활동기록 상세 뷰컨트롤러로 이동 및 라벨 수정 가능하게 함
- [x] 활동기록 상세에서 해당 활동기록의 이미지를 불러오는 함수 구현
