### ISSUE TITLE
[Feat/Fix]#29 - 맵뷰 버튼 및 경로 함수 적용

### ISSUE THREAD

**Issue by VesselWheel** [Run-Eat/Run-It#29]
## To-do

- [x] 러닝맵뷰 버튼 UI와 레이아웃 수정 및 하프모달 적용
- [x] 맵뷰 경로 함수 적용(test)
- [x] 맵뷰-러닝기록뷰 간의 버튼과 연결 수정
