### ISSUE TITLE
[Feat]#46 - 러닝타이머뷰~러닝맵뷰 간의 페이지 컨트롤러 적용

### ISSUE THREAD

**Issue by VesselWheel** [Run-Eat/Run-It#46]
## To-do

- [x] 러닝타이머뷰~러닝맵뷰 간의 페이지 컨트롤러 적용
- [x] 페이지컨트롤러로 진입한 러닝맵뷰에서 러닝타미머뷰로 되돌아 가는 버튼 생성, 러닝시작 버튼 숨김
- [x] 테마 색은 .systemIndio와 .systemTeal 적용
- [x] 도착지 어노테이션 원복 코드 수정

**Comment by VesselWheel** [comment]
테마 색은 .systemIndio와 .systemTeal 입니다. 
![스크린샷 2024-03-07 12 50 55](https://github.com/Run-Eat/Run-It/assets/88497383/794d6467-2174-4a68-9292-f6d213837810)
![스크린샷 2024-03-07 12 51 03](https://github.com/Run-Eat/Run-It/assets/88497383/dfb28f93-511a-4468-bc10-1ade0f8c6c6b)
![스크린샷 2024-03-07 12 53 15](https://github.com/Run-Eat/Run-It/assets/88497383/6960b5d3-e69b-4eb2-9c02-ca44eb8d8ea6)
![스크린샷 2024-03-07 12 53 55](https://github.com/Run-Eat/Run-It/assets/88497383/85f77665-83ff-4f2e-b817-831bf44b3735)
![스크린샷 2024-03-07 12 53 47](https://github.com/Run-Eat/Run-It/assets/88497383/630e7c7b-b0a9-4874-ba30-502b1dabfd5c)
