### ISSUE TITLE
[Feat]#5 - 러닝기록UI 구현

### ISSUE THREAD

**Issue by VesselWheel** [Run-Eat/Run-It#5]
## To-do

- [x] 시간, 페이스, 거리, 시간 레이블 
- [x] 하프 모달 내 러닝기록 레이블과 재시작, 정지 버튼 추가
- [x] 러닝기록 매소드 : 러닝 시작, 러닝 종료 등

**Comment by VesselWheel** [comment]
![스크린샷 2024-02-23 12 19 29](https://github.com/Run-Eat/Run-It/assets/88497383/b6d61eb7-744e-4aa4-b7ef-d0955c77103e)

**Comment by VesselWheel** [comment]
<img width="315" alt="스크린샷 2024-02-23 19 46 42" src="https://github.com/Run-Eat/Run-It/assets/88497383/9e84ef02-cd56-485f-896f-4d5846a22d29">

**Comment by VesselWheel** [comment]
https://youtube.com/shorts/Yyx4Kdm_4-g?feature=share

**Comment by VesselWheel** [comment]
UI만 우선 구현, 러닝기록 타이머 로직은 지속 개발 중
