### ISSUE TITLE
[Feat]#54 - 스토어하프모달뷰생성

### ISSUE THREAD

**Issue by futuremouse** [Run-Eat/Run-It#54]
## To-do

- [x] 하프모달뷰 리스트 구성
- [x] 하프모달뷰 어노테이션 정보 가져오기
- [x] 즐겨찾기 추가
- [x] 즐겨찾기 이미지 추가

**Comment by futuremouse** [comment]
<img width="314" alt="스크린샷 2024-03-08 오전 12 12 30" src="https://github.com/Run-Eat/Run-It/assets/151702566/678a8461-0e3c-4607-9560-26ea65e531f0">

<img width="311" alt="스크린샷 2024-03-08 오전 12 50 16" src="https://github.com/Run-Eat/Run-It/assets/151702566/5adad7c4-da1f-4a78-b87f-6a5dad520bf9">

<img width="305" alt="스크린샷 2024-03-08 오전 9 59 35" src="https://github.com/Run-Eat/Run-It/assets/151702566/f96e3218-41f3-444f-ac56-6ef5d34a4d24">

1. 모달뷰생성
2. 닫기버튼 추가 - 닫기하면 어노테이션 생성 (추후 제스처 등으로 변경예정)
3. 즐겨찾기 추가 기능
