### ISSUE TITLE
[Feat]#56 - annotation 개선

### ISSUE THREAD

**Issue by VesselWheel** [Run-Eat/Run-It#56]
## To-do

- [x] 지도 화면 전환 시 사용자 위치 중심으로 오도록 수정
- [x] #60
- [x] 색 테마 적용(상단뷰 - systemBlue, 하단뷰 - systemIndio, 러닝타이머 - systemYellow
- [x] 앱 아이콘, 도착지 annotation asset 추가
- [x] LaunchScreen 적용
