### ISSUE TITLE
[Fix]#68 - 스냅샷이미지 크기설정

### ISSUE THREAD

**Issue by futuremouse** [Run-Eat/Run-It#68]
## To-do

- [x] 스냅샷이미지 경로에 따른 지도크기조정확인
- [x] 스냅샷 활동리스트에 추가
- [x] 스냅샷 활동상세뷰컨트롤러에 이미지 크기 동적 조정
