### ISSUE TITLE
[Feat]#7 - 이벤트페이지 UI 구현

### ISSUE THREAD

**Issue by futuremouse** [Run-Eat/Run-It#7]
## To-do
- [x] 레이아웃 스냅킷으로 적용
- [x] 네비게이션 바 적용
- [x] 섹션 2개로 진행
- [x] custom 테이블뷰셀 사용
- [x] #16

**Comment by futuremouse** [comment]
<img width="304" alt="스크린샷 2024-02-24 오후 4 00 48" src="https://github.com/Run-Eat/Run-It/assets/151702566/d0e86588-0b8d-4288-b88b-110f3506411d">
