### ISSUE TITLE
[Fix]#79 - 프로필뷰로딩개선

### ISSUE THREAD

**Issue by futuremouse** [Run-Eat/Run-It#79]
## To-do

- [x] 프로필뷰 크기 정렬
- [x] 상세기록 정렬
- [x] 활동기록 List 테이블뷰셀 UI 업데이트 피로도 감소
- [x] 러닝타이머 시작함수 수정 (nil일때 바로시작)
- [x] 화면전환방식 수정 - 델리게이트 내용 추가(모달뷰에서 탭바화면으로 전환할때 모든 present된 view 제거)
