### ISSUE TITLE
[Fix]#83 - 러닝 맵뷰 UI 개선

### ISSUE THREAD

**Issue by VesselWheel** [Run-Eat/Run-It#83]
## To-do

- [x] 버튼 UI 개선(쉐도우, 크기 조절)
- [x] 러닝 타이머 버튼 색 변경 인디고 -> 블루
- [x] 러닝맵뷰 사용자 위치 관련 setUserTrackingMode를 followWithHeading 변경하여 기기 방향 적용
