### ISSUE TITLE
[Feat]#90 - ExpandKindOfStore

### ISSUE THREAD

**Issue by VesselWheel** [Run-Eat/Run-It#90]
## To-do

- [x] 업체 정보 확장 편의점(CU, 이마트 24, GS25 등)
- [x] 업체 정보 확장 카페(스타벅스, 투썸플레이스, 이디야 등)
- [x] 업체 정보 확장 건강식(샐러디, 서브웨이 등)
