### ISSUE TITLE
[Feat]#94 - 사용자 위치추적 사용시간 제한

### ISSUE THREAD

**Issue by VesselWheel** [Run-Eat/Run-It#94]
## To-do

- [x] 사용자 위치추적 사용시간 제한
- [x] 프로필뷰 주간, 월간 버튼 디자인 적용
- [x] 불필요 코드 정리
